INSTALLED_RECOVERY_RAMDISK_TARGET := $(PRODUCT_OUT)/prebuilt-ramdisk-recovery.img

INTERNAL_RECOVERYIMAGE_ARGS := \
	--kernel $(INSTALLED_KERNEL_TARGET) \
	--ramdisk $(INSTALLED_RECOVERY_RAMDISK_TARGET)

INTERNAL_RECOVERYIMAGE_FILES := $(filter-out --%,$(INTERNAL_RECOVERYIMAGE_ARGS))

INTERNAL_RECOVERYIMAGE_ARGS += \
	--cmdline "$(INTERNAL_KERNEL_CMDLINE)" \
	--base $(BOARD_KERNEL_BASE) \
	--pagesize $(BOARD_KERNEL_PAGESIZE)

$(INSTALLED_RECOVERY_RAMDISK_TARGET): $(BOARD_PREBUILT_RECOVERY_RAMDISK)
	cp $(BOARD_PREBUILT_RECOVERY_RAMDISK) $@

$(INSTALLED_BOOTIMAGE_TARGET): $(MKBOOTIMG) $(INTERNAL_RECOVERYIMAGE_FILES) $(RECOVERYIMAGE_EXTRA_DEPS)
	$(call pretty,"Target boot image from recovery: $@")
	$(hide) $(MKBOOTIMG) \
		$(INTERNAL_RECOVERYIMAGE_ARGS) \
		$(INTERNAL_MKBOOTIMG_VERSION_ARGS) \
		--output $@ \
		--id > $(RECOVERYIMAGE_ID_FILE)
	$(hide) $(call assert-max-image-size,$@,$(BOARD_BOOTIMAGE_PARTITION_SIZE))
